export const URGENCY_PHRASES: readonly string[] = [
  "act now",
  "verify your account",
  "click here immediately",
  "account suspended",
  "limited time offer",
  "immediate action required",
  "urgent notification",
  "security breach",
  "unauthorized access",
  "action needed",
  "account locked",
  "suspended within 24 hours",
  "verify identity",
  "update immediately",
  "final notice",
  "payment failed",
  "suspension warning",
];

export const BRAND_IMPERSONATION_TOKENS: readonly string[] = [
  "collabstr",
  "hmrc",
  "irs",
  "usps",
  "fedex",
  "dhl",
  "netflix",
  "apple id",
  "apple",
  "paypal",
  "amazon",
  "your bank",
  "chase",
  "wells fargo",
  "bank of america",
  "barclays",
  "santander",
  "microsoft",
  "meta",
  "whatsapp",
  "google",
  "binance",
  "coinbase",
  "steam",
  "telegram",
  "discord",
];

export const CREDENTIAL_HARVEST_PHRASES: readonly string[] = [
  "enter your password",
  "confirm your details",
  "update your billing",
  "verify now",
  "login here",
  "sign in to review",
  "reset password",
  "enter your credentials",
  "confirm passcode",
  "verify pin",
  "claim your refund",
  "claim prize",
  "wallet phrase",
  "seed phrase",
  "credit card",
];

export const SHORTENER_PATTERNS: readonly RegExp[] = [
  /https?:\/\/(?:www\.)?bit\.ly\/[a-zA-Z0-9_-]+/i,
  /https?:\/\/(?:www\.)?tinyurl\.com\/[a-zA-Z0-9_-]+/i,
  /https?:\/\/(?:www\.)?t\.co\/[a-zA-Z0-9_-]+/i,
  /https?:\/\/(?:www\.)?ow\.ly\/[a-zA-Z0-9_-]+/i,
  /https?:\/\/(?:www\.)?is\.gd\/[a-zA-Z0-9_-]+/i,
  /https?:\/\/(?:www\.)?cutt\.ly\/[a-zA-Z0-9_-]+/i,
  /https?:\/\/(?:www\.)?rb\.gy\/[a-zA-Z0-9_-]+/i,
];
